frontend:
  build: .
  working_dir: /app
  command: npm run build
  volumes:
    - ./app:/app
  ports:
   - "3000:3000"


nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./app:/app
    - ./conf/app.conf:/etc/nginx/conf.d/app.conf